// AUTO-GENERATED by backend/scripts/iap/generate_ts_constants.py
// Source of truth: backend/app/iap/subscriptions_list.py
// DO NOT EDIT BY HAND — regenerate via boot.sh or `uv run scripts/iap/generate_ts_constants.py`.

export type SubscriptionTier = "family" | "individual";
export type SubscriptionCycle = "monthly" | "yearly";

export type Subscription = {
  tier: SubscriptionTier;
  cycle: SubscriptionCycle;
  appleProductId: string;
  targetUsdPrice: string;
  stripePriceSandbox: string;
  stripePriceLive: string;
};

export const SUBSCRIPTIONS: readonly Subscription[] = [
  {
    tier: "individual",
    cycle: "monthly",
    appleProductId: "com.palkietalkie.individual.monthly",
    targetUsdPrice: "17.99",
    stripePriceSandbox: "price_1Tb7Wa5kJkygJqGZq0o4ssGx",
    stripePriceLive: "price_1Tb7Wb8n3tBguXEAXS1NVSjH",
  },
  {
    tier: "individual",
    cycle: "yearly",
    appleProductId: "com.palkietalkie.individual.yearly",
    targetUsdPrice: "83.99",
    stripePriceSandbox: "price_1TfBGv5kJkygJqGZhvE2hah8",
    stripePriceLive: "price_1TfBGw8n3tBguXEAPk0aTAeQ",
  },
  {
    tier: "family",
    cycle: "monthly",
    appleProductId: "com.palkietalkie.family.monthly",
    targetUsdPrice: "19.99",
    stripePriceSandbox: "price_1Tb7Wa5kJkygJqGZUxd7pwlV",
    stripePriceLive: "price_1Tb7Wb8n3tBguXEAlICYGxRt",
  },
  {
    tier: "family",
    cycle: "yearly",
    appleProductId: "com.palkietalkie.family.yearly",
    targetUsdPrice: "112.99",
    stripePriceSandbox: "price_1TfBGv5kJkygJqGZLMnKV36G",
    stripePriceLive: "price_1TfBGw8n3tBguXEAITu8xy3X",
  },
] as const;

/** Returns the right Stripe price id for the active deploy. APP_ENV / Vercel `NODE_ENV` decides. */
export function stripePriceFor(tier: SubscriptionTier, cycle: SubscriptionCycle): string {
  const p = SUBSCRIPTIONS.find((x) => x.tier === tier && x.cycle === cycle);
  if (!p) throw new Error(`Unknown subscription: ${tier} ${cycle}`);
  const env = process.env.APP_ENV ?? process.env.NODE_ENV ?? "development";
  return env === "production" ? p.stripePriceLive : p.stripePriceSandbox;
}
